# Generated by Django 3.1.5 on 2021-02-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Books',
            fields=[
                ('Book Id', models.AutoField(primary_key=True, serialize=False)),
                ('Book Title', models.CharField(max_length=30, unique=True)),
                ('Author', models.CharField(blank=True, max_length=30)),
                ('Issue Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Issued_Books',
            fields=[
                ('Book Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='index.all_books')),
                ('User Issued', models.CharField(max_length=30)),
                ('Date Issued', models.DateField(auto_now=True)),
            ],
        ),
    ]
