# Generated by Django 3.1.5 on 2021-02-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210224_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issued_books',
            name='Book Id',
        ),
        migrations.DeleteModel(
            name='All_Books',
        ),
        migrations.DeleteModel(
            name='Issued_Books',
        ),
    ]
