# Generated by Django 3.1.5 on 2021-02-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0003_auto_20210225_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Books',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=30, unique=True)),
                ('author', models.CharField(blank=True, max_length=30)),
                ('istatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Issued_Books',
            fields=[
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='index.all_books')),
                ('uissued', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
