# Generated by Django 3.1.5 on 2021-02-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_all_books_issued_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_books',
            name='bid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
