# Generated by Django 3.1.5 on 2021-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210225_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_books',
            name='istatus',
            field=models.BooleanField(default=True),
        ),
    ]
