# Generated by Django 3.1.5 on 2021-02-27 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210226_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Books',
            fields=[
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='index.all_books')),
                ('btitle', models.CharField(max_length=30, unique=True)),
                ('author', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='issued_books',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='index.all_books'),
        ),
    ]
