# Generated by Django 3.1.5 on 2021-02-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20210227_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_books',
            name='bid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issued_books',
            name='bid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
