# Generated by Django 3.1.5 on 2021-03-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210228_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='istatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='uissued',
            new_name='user',
        ),
    ]
