# Generated by Django 3.1.5 on 2021-03-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210302_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
