# Generated by Django 3.1.5 on 2021-03-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_books_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='fine',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
